language: ruby
script: "bundle exec jekyll build"
before_install:
  - 'gem update --system --conservative || (gem i "rubygems-update:~>2.7" --no-document && update_rubygems)'
  - 'gem update bundler --conservative'
branches:
  except:
    - master
dist: trusty
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
cache: bundler
sudo: false
